name: CI/CD


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test
        run: mvn clean test
      - name: Compile
        run: mvn compile
      - name: Build JAR
        run: mvn package
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: Bank-System
          path: target/bank-system-1.jar







