name: CI/CD


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "The job was triggered on ${{github.event_name}}"
      - run: echo "The branch was ${{github.ref}}"
      - run: echo "The os this was run on is ${{runner.os}}"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test with Maven
        run: mvn clean test
      - name: Compile with Maven
        run: mvn compile
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
